defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://transmission.*"
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl.crt"
      keyFile = "/etc/traefik/ssl.key"
    [entryPoints.https.auth]
      [entryPoints.https.auth.basic]
      users = [
        "googol:$apr1$21V9eoxN$xwcW8ud3rHKr4gsVWwHx0.",
      ]

[docker]
domain = "googol.im"
endpoint = "unix:///var/run/docker.sock"
watch = true

[api]
entryPoint = "https"
dashboard = true
